#!/bin/bash
ip=`cat /home/ansible/ips.txt`
TOKEN="6630831950:AAEVYgMjXYT-uIWvCWAM2NqSwbuMyxfeXbk"
CHAT_ID="-1001825783653"
#message="Hello Guys server ip with $ip is not working please check"
for j in $ip
do
        ping -c1 $j &> /dev/null

        if [ $? -eq 0 ]
        then
                echo "Machine is with $j is  ok"
        else
curl -X POST https://api.telegram.org/bot$TOKEN/sendMessage  -d chat_id=$CHAT_ID -d text="Hello Guys server ip with $j is not working please check">/dev/null

        fi
done
